version: '3'

services:

  lightbo.lt-base:
    image: lightbo.lt-base:latest
    container_name: lihtbo.lt-base
    ports:
      - 13000:3000
    networks:
      - lightbo.lt-network
    depends_on:
      - lightbo.lt-db

  lightbo.lt-db:
    image: lightbo.lt-db:latest
    container_name: lightbo.lt-db
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - lightbo.lt-db-data:/var/lib/mysql
    networks:
      - lightbo.lt-network
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'homereset'
      MYSQL_USER: 'homereset'
      MYSQL_PASSWORD: 'quertyhomerest'
      MYSQL_DATABASE: 'homerest'

volumes:
  lightbo.lt-db-data:

networks:
  lightbo.lt-network:
